alecthomas/chroma

- cmd/chroma/main.go
> support windows colors

- lexers/gdscript.go
GDScript is the language used by the godot game engine [https://godotengine.org/](https://godotengine.org/)
> Add GDScript lexer

- lexers/csharp.go
> Add c# lexer

- lexers/toml.go
Adding support for [TOML](https://github.com/toml-lang/toml) syntax highlighting.
> Add lexer for TOML

- lexers/nix.go
I started by converting a pygments lexer with `pygments2chroma.py`, then rewrote everything. I've confirmed with #50 that it parses all `.nix` files in https://github.com/NixOS/nixpkgs , and when looking at the results of various pages I do not see anything unintended.
> Add Nix lexer

- cmd/chroma/main.go
This pull request adds an option to check tokenization and print file positions that failed to tokenize. It proved invaluable at the final stage of development of my tokenizer for the Nix language (#51), when I ran `find . -name '*.nix' | xargs -n50 -P4 chroma --check` on the repository that currently hosts 10000 Nix files and fixed intricate bugs that I wouldn't have spotted by looking at random `--html` results.
The implementation is slightly rough, I guess you'd want to refactor it. I've added a new option rather than a new formatter because I want to output file names, and because it would be fairly difficult to guess looking at `--help` that `chroma` supports this functionality if it were just another formatter.
> Add --check flag to aid in lexer development

- lexers/systemverilog.go
- lexers/verilog.go
Fixes https://github.com/alecthomas/chroma/issues/55
> Add newline at eof for (system)verilog lexers

- cmd/chroma/main.go
- formatters/html/html.go
- types.go
> Add table styled line numbers

- quick/example_test.go
- quick/quick.go
> quick: add an example

- lexers/markdown.go
(Yeah I know, but they are out there ;)
> Allow .mkd and .markdown

- lexers/csharp.go
Implement Point2 discussed in #68
> Catch some static class in csharp lexer

- README.md
I spotted it while looking over the README.
> README: Fix typo.

- lexers/http.go
Http lexer based on pygments HttpLexer
https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/textfmts.py?at=default&fileviewer=file-view-default#textfmts.py-113
> Add http lexer

- lexers/diff.go
- lexers/diff_test.go
> Ensure newline in diff lexer

- formatters/html/html.go
- formatters/html/html_test.go
Strip leading semicolons in combination with line numbers.
fixes #98
> Fix broken css rules output

- lexers/h/http.go
Hi,
Thanks for the fantastic project! We're using it for our mitmproxy docs (e.g. [here](https://mitmproxy.org/docs/latest/concepts-howmitmproxyworks/)) and are super happy with that. One thing we noticed is that it doesn't properly highlight CONNECT requests, so here's a PR to fix that. 😃
> http: add CONNECT method

- README.md
> Add link to the Chroma Style Gallery

- cmd/chroma/main.go
- formatters/html/html.go
Since this was a small issue i tried to implement this myself. Im not fluent in go so feedback is appreciated!
Should fix my own ticket #173
> Add option to prevent surrounding pre tags

- .goreleaser.yml
See: https://github.com/goreleaser/goreleaser/pull/787  
and  
https://github.com/goreleaser/goreleaser/pull/1282
(Prettified the yaml a bit too)
> Fix deprecated methods in goreleaser.yml

- go.mod
> Remove reference to now unneeded go.rice fork from go.mod

- .goreleaser.yml
Fixes #327 unless I'm missing something :)
> generate static binaries with goreleaser

- lexers/j/javascript.go
- lexers/testdata/javascript.actual
- lexers/testdata/javascript.expected
https://tc39.es/ecma262#table-string-single-character-escape-sequences
Fixes #414
> JavaScript: String Single Character Escape Sequences

- lexers/h/handlebars.go
- lexers/j/javascript.go
- lexers/p/powershell.go
These should be pretty clear cases.
> Add various alternate file extensions to lexers

- styles/nord.go
This commit adds the Nord theme as an option. This theme is fully documented in the official website: https://www.nordtheme.com
> Introduce the Nord theme

- styles/vulcan.go
This is a new theme / style, inspired by Doom Emacs's One Doom Theme
> Add new style - "vulcan"

- README.md
Was labelled as pygments-lexers.go
> Fix link to pygments-lexers.txt

- lexers/p/python.go
- lexers/p/python2.go
Oups, MimeTypes were inconsistent (follows #489)…
> Use Python 3 by default (finish the job)

- README.md
- lexers/g/groff.go
Generated from Pygments one, some filename extensions added.
> lexers: add one for groff

- regexp.go
Makes it easier to use a captured group's content. Currently mostly useful for `Mutators`,
But I will make another pull request to pass `LexerState` to `Emitters`. Then It can
be useful for `Emitters` as well.
> Add support for named capture groups

- styles/doom-one.go
it was close to operator's color
> [doom-one] Change style of `NameAttribute`

- styles/hr_dark.go
- styles/hr_high_contrast.go
A new style , inspired by `HackerRank`.
Themes:
* [Dark](https://github.com/soubikbhuiwk007/chroma/blob/style-hr/styles/hr_dark.go)
* [High Contrast](https://github.com/soubikbhuiwk007/chroma/blob/style-hr/styles/hr_high_contrast.go)
> Add new style - "hr"

- formatters/html/html.go
- formatters/html/html_test.go
Closes https://github.com/alecthomas/chroma/issues/514
> Add tabindex="0" to default <pre> wrapper

- lexers/m/mysql.go
Fixes: https://github.com/alecthomas/chroma/issues/590
> Add mariadb aliases

- lexers/embedded/fortran.xml
Revised the fortran lexer to be consistent with the current version in pygments
> Update fortran lexer

- go.mod
- go.sum
- Bump repr to v0.1.0
- Bump testify to v1.8.0
> Bump testify, repr to the latest version

- styles/gruvbox-light.go
> Add Gruvbox light theme

- lexers/embedded/typescript.xml
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#new-file-extensions
> Add .mts,.cts to typescript lexer

- lexers/embedded/ini.xml
Reference: https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#command-line-options
> Add .pylintrc to ini lexer

- emitters.go
Bringing into line the documentation with the changed API for
UsingByGroup.
> Update UsingByGroup documentation

- styles/rose-pine-dawn.xml
- styles/rose-pine-moon.xml
- styles/rose-pine.xml
GenericSubHeading should be Iris color.
> Update Rose-pine styles

- lexers/embedded/c.xml
I pushed the changes I mentioned on #698. Unfortunately I'm not expert enough to understand where there're tests for C language. I probably have missed it.
> General improvements to C lexer

- styles/onedark.xml
> Create One Dark theme

- formatters/html/html.go
> Add `-webkit-user-select: none;` to support Safari

- formatters/html/html.go
- formatters/html/html_test.go
> Removes 'tabindex="0"' from `<pre>` elements

- lexers/embedded/groovy.xml
You can check the release notes if needed:
https://groovy-lang.org/releasenotes/groovy-4.0.html
> Groovy added a 'record' type and keyword in version 4

- lexers/http.go
- lexers/testdata/http.2.0.actual
- lexers/testdata/http.2.0.expected
- lexers/testdata/http.3.actual
- lexers/testdata/http.3.expected
> support HTTP/2 and HTTP/3

- lexers/embedded/go_template.xml
See https://pkg.go.dev/text/template#hdr-Functions
> lexers/go_template: Add missing global functions

- lexers/embedded/d.xml
Add missing keywords, remove non-keywords, move a few things around to where they make more sense to be.
References:
- https://dlang.org/spec/lex.html#keywords
- https://dlang.org/spec/lex.html#specialtokens
- https://dlang.org/phobos/object.html
> lexers/d: Update keyword lists

- lexers/embedded/dns.xml
Support for .zone extension:
https://en.wikipedia.org/wiki/Zone_file
> Add file support for BIND DNS Zone

- cmd/chroma/go.mod
- cmd/chroma/go.sum
- cmd/chromad/go.mod
- cmd/chromad/go.sum
Update go modules to the latest versions.
> deps: update go modules

- lexers/embedded/r.xml
This PR increases the priority for `R` lexer over Rebol.
> R lexer has priority over Rebol

- lexers/embedded/mathematica.xml
This PR adds missing file extensions to Mathematica lexer.
> Add new file extensions to Mathematica lexer

- lexers/embedded/hlsl.xml
To match GitHub's linguist https://github.com/github-linguist/linguist/blob/916bd8f3df802fa98b0ea85539e67bd0b88ef158/lib/linguist/languages.yml#L2623
> Add more hlsl file extensions

- lexers/embedded/prql.xml
I generated this file with the `pygments2chroma_xml.py` script.
PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement.
https://prql-lang.org/
https://github.com/PRQL/prql
> Add PRQL language

- styles/evergarden.xml
Add [`evergarden`](https://github.com/comfysage/evergarden) style.
> chore(styles): add evergarden inspired style

- lexers/embedded/toml.xml
Ref: https://docs.astral.sh/uv/guides/projects/#uvlock
> Add `uv.lock` to TOML lexer

- styles/catppuccin-frappe.xml
- styles/catppuccin-latte.xml
- styles/catppuccin-macchiato.xml
Follow up to https://github.com/alecthomas/chroma/pull/1094; if we update one of the four Catppuccin flavors we should update the other three at the same time for consistency sake.
> Sync Catppuccin styles

- serialise.go
> Analyse() now cares about case-insensitivity

- lexers/embedded/rpgle.xml
Small fix for an analysis regex in RPGLE lexer.
> Fixed **free analysis in RPGLE
