alecthomas/chroma

- cmd/chroma/main.go
This PR fixes a problem that go-colorble does not work after cc0e4a59ab3a20edf6efea25b49952f8555cae52.
> Fix colors on windows

- lexers/capnproto.go
I found a HTML entity reference in lexer name. I fixed `&#x27;` to `'`.
> fix HTML entity reference

- lexers/mwscript.go
After testing on various scripts from Morrowind, I have not noticed anything broken, though I most certainly intend to rework and clean up the regex when possible.  Example script below:
```Begin GG_OpenGate1
;opens first gate as Ghostgate (say that 5 times)
;put on button
float timer
short state
if ( MenuMode == 1 )
return
endif
if ( OnActivate == 1 )
if ( GG_Gate1_State == 0 ) 
PlaySound "Open Lock"
"ex_gg_portcullis_01"->Playsound3DVP "Dwemer Door Open" 1.0 1.0
set GG_Gate1_State to 10
set state to 10
endif
endif
if ( State >= 10 )
set timer to ( timer + GetSecondsPassed )
;move gate up (210 units)
if ( timer < 3 )
"ex_gg_portcullis_01"->MoveWorld z 70
;set back to start
elseif ( timer > 21 )
"ex_gg_portcullis_01"->SetAtStart
set State to 0
;can now press button again
set …
```
> Added basic Morrowind Scripting parsing

- cmd/chroma/main.go
Changes output for the chroma cli tool for styles and formatters so that
the output on --list is always in the same order.
> Fix order output of chroma cli tool

- formatters/html/html.go
- formatters/html/html_test.go
This PR adds a single method `HasClasses` that returns `true` if the `WithClasses()` functional option was used. Also adds a small test to validate the usage.
> Adding HasClasses method for HTML formatter

- formatters/html/html.go
This commits adds a div wrapper when linenumbers are formatted in table, to get the correct CSS matchers.
This commit also fixes some CSS table issues when tables are put into a larger context with other stylesheets:
* No borders.
* Overflow to fit in potentially narrower containers.
Fixes #62
> Add a chroma class wrapper when in "table mode"

- formatters/tty_truecolour.go
Most terminals seems to use semicolons in true colors:
https://gist.github.com/XVilka/8346728
> Changed terminal16m to semicolons

- cmd/chroma/main.go
cgit's syntax highlighting filter pipes to STDIN and provides the
filename in argv; the analyzer often fails but we have access to the
original filename, so we add an optional argument to specify the
filename to use for matching a lexer when reading from STDIN; when
[files...] are provided to chroma this is completely ignored
> Select lexer with --filename argument

- README.md
- doc.go
Just a minor typo that I noticed in the process of packaging chroma for Debian.
Many thanks!
> Fix typo: translater → translator

- formatters/html/html.go
> fix `func compressStyle(s string)` for CSS Shorthand properties

- formatters/html/html.go
- formatters/html/html_test.go
Currently `html.ClassPrefix()` sets `f.prefix`, but nothing in the rendering path reads this value. This PR emits the prefix when rendering element class names and the CSS styles.
> Render HTML class prefixes.

- formatters/html/html.go
- formatters/html/html_test.go
Since these are wrapped in a `<pre>`, newlines hint the browser that the
line numbers should be on separate lines. This helps when rendering
content with broken CSS, or in a text-only browser.
See attached screenshot for a before/after comparison in `w3m`. A similar improvement exists for modern browsers (Firefox, Chrome) when viewing a page that failed to load its CSS.
> Add newlines in line number spans when wrapping in an HTML table.

- formatters/html/html.go
- formatters/html/html_test.go
This makes the raw markup a bit cleaner when there's lots of `Text`
tokens.
> Avoid adding an HTML prefix to empty class names.

- lexers/internal/api.go
- lexers/p/plaintext
- lexers/p/plaintext.go
In Hugo (and probably similar applications), markdown code blocks are always highlighted.
Sometimes users put plaintext in these boxes, so it is useful to have a simple lexer for it. 
This is `no-highlight` in highlight.js.
> create plaintext lexer

- styles/solarized-dark.go
- styles/solarized-dark256.go
- styles/solarized-light.go
It looks like solarized styles are required by people, for ex: [one](https://discourse.gohugo.io/t/converting-pygments-styles-to-chroma/11561), [two](https://themes.gohugo.io/hugo-octopress/) ↓
> However, Chroma does not support the pygments solarized dark style. It’s added to the CSS instead ...
I also need it for for migration from highlight.js to chroma in [another hugo theme](https://github.com/xianmin/hugo-theme-jane).
I've already got required css styles with tool I proposed in #139, but I think it'd be useful to have solarized themes bundled into chroma itself too.
> ✨ New styles from solarized styles family

- lexers/c/cpp.go
C++ highlighting ignores class keyword if it is not followed by a space
```cpp
template<class T> struct X; // ok
template<class> struct X; // fails
template<class...> struct X; // fails
X<class::Y> x; // fails
```
> c++: fix highlighting of the 'class' keyword

- formatters/html/html.go
- styles/autumn.go
- styles/borland.go
- styles/colorful.go
- styles/dracula.go
- styles/emacs.go
- styles/friendly.go
- styles/github.go
- styles/lovelace.go
- styles/manni.go
- styles/murphy.go
- styles/native.go
- styles/pastie.go
- styles/perldoc.go
- styles/pygments.go
- styles/rainbow_dash.go
- styles/tango.go
- styles/trac.go
- styles/vim.go
- types.go
'l' in gl is for under(l)ine, as the "gu" class is taken by
GenericSubheading.
As I later discover the `GenericUnderline` type that I requested in https://github.com/alecthomas/chroma/issues/159 is already declared in types.go; just that no CSS class is reserved for it. This PR adds that.
~~Should I simply add `chroma.GenericUnderline:     "underline",` to all the *styles/\*.go* files?~~ No, turns out, I also had to tweak `formatters/html/html.go`.
Fixes https://github.com/alecthomas/chroma/issues/159.
> Assign .gl class to GenericUnderline

- lexers/b/bash.go
This pull request proposes a change to the Bash lexer to fix issue #168 .
Before the fix the bash lexer generated this HTML output:
~~~html
<!DOCTYPE html><html><head><link rel='stylesheet' href='style.css'></head><body><pre class="chroma">
<span class="c1"># Install fish
</span><span class="c1"></span>
brew install fish
<span class="c1"># Add fish to your list of available shells
</span><span class="c1"></span>
<span class="nb">echo</span> <span class="s2">&#34;/usr/local/bin/fish/&#34;</span> <span class="p">|</span> sudo tee -a /etc/shells
<span class="c1"># Make fish the defaul shell
</span><span class="c1"></span>
chsh -s /usr/local/bin/fish
~~~
The problem is that the last line (the `#` comment) isn't recognised as a comment.
With the fix in this pull request the output becomes: …
> Fix error with Bash lexer (issue #168)

- README.md
For this pull request I went through all lexers files that Chroma got and added the missing ones to the lexers table in the README file. The ones I found missing in the README were: Cassandra SQL, Jungle, MonkeyC, Plaintext, OpenSCAD, and systemd.
This pull request also alphabetically lists the lexers. And the third and last change made by this pull request is to center the first column of the table (purely ascetic).
> Add missing lexers to README

- lexers/t/tradingview.go
I overlooked the `to` keyword earlier when making the TradingView lexer. This pull request adds that previously missing keyword to the lexer.
(Have a nice weekend. :slightly_smiling_face: )
> Add missing 'to' keyword to TradingView lexer

- lexers/y/yaml.go
This pull request fixes the issue reported with the pipe symbol (`|`) in #194 . 
Since `|` can signal a multi-line string (or scalar block as YAML calls it) besides appearing regular in strings, this pull request proposes to only consider it a string when `|` marks the end of the line (or, put differently, the start of a scalar block).
Before:
After:
> Fix YAML pipe symbol (issue #194)

- lexers/c/csharp.go
- lexers/t/tradingview.go
- lexers/testdata/csharp.actual
- lexers/testdata/csharp.expected
- lexers/testdata/tradingview.actual
- lexers/testdata/tradingview.expected
This pull request:
- Enables the `EnsureNL` option for the TradingView and C# lexer. This way when a comment is the last line of a code snippet, that comment gets highlighted properly.
- Adds a test comment as last line to the TradingView and C# testdata files.
- Updates the expected output of those two testdata files.
However, I marked this pull request as 'Work in progress' because I see in the rendered testdata that there's a new line (`\n`) added to the end of the testdata output. I don't know enough about how Chroma operates to interpret that this means that the *'add a complete new line to highlighted blocks'* issue [mentioned earlier](https://github.com/alecthomas/chroma/pull/215#issuecomment-455104348) still applies.
This pull request, when successful, closes #214 and #215.
> [WIP] Enable EnsureNL for TradingView and C# lexers

- README.md
When we discussed a recent pull request (#219), it came up that `chroma.Background` defines the default token style. And that tokens in a style file are hierarchical.
This pull request adds that information to the README file to clarify this for others. And to save explaining the same thing in the future again.
> Add additional information about style to README

- lexers/j/javascript.go
This pull request makes a small change to the JavaScript lexer to not recognise the second part of a division as a regex start.
Big thanks to @davidfeng88 who in [his earlier comment](https://github.com/alecthomas/chroma/issues/125#issuecomment-455902797) identified what caused the problem. That made it much easier for me to make the necessary adjustment.
----
I took the liberty to open this pull request since I don't know if David wanted to open a PR for this issue. It was his find after all, so he should deserve the credit. 
But since his comment was almost 2 weeks ago, I thought this pull request was appropriate. If he want to propose his own PR, feel free to discard mine!
----
Closes #125.
> Fix JS second part of division expression

- lexers/j/jsx.go
This fixes broken highlighting for tags like
```
<React.Fragment>
{...}
</React.Fragment>
```
> modify jsx lexer to handle tags with periods

- lexers/p/prolog.go
Inline comments are % in Prolog as on old Line 20, not #. Also raised an issue in Pygments.
> Removed # as a comment character from Prolog lexer

- lexers/t/typescript.go
Fixes #267 
Add `EnsureNL:  true` in TypeScript lexer config as JavaScript has.
> Add EnsureNL in TypeScript lexer config

- styles/pygments.go
- styles/swapoff.go
I've notices `type StyleEntries` is not used at some styles. For consistency with other styles, I've changed `map[chroma.TokenType]string` to `chroma.StyleEntries`.
> Use `chroma.StyleEntries` instead of map

- formatters/tty_indexed.go
- formatters/tty_truecolour.go
This PR is a bit of a request for feedback. I made the smallest change to support my use-case
for emitting italics, namely limiting it to terminals which claim to support truecolour.
It's possible this change should be replicated in tty_indexed.go as well. (Perhaps some indexed color terminal emulators support italics?) I'm happy to add that change if that's preferred, but I don't have an example emulator to point to where that's true.
Below is a screenshot with the change in iTerm2 and Source Code Pro, showing `go doc ioutil | chroma -f terminal16m -s algol`
> Add italics support for truecolour terminals

- lexers/n/nim.go
This pull request adds a multi-line comment rule to the Nim lexer, as requested in #284.
---
I ran the tests locally, and the Nim test data remained the same. That's why this pull request doesn't change the test data.
Closes #284
> Add multi-line comments to Nim lexer

- cmd/chroma/main.go
- formatters/api.go
- formatters/svg/svg.go
basic version without any options. colors and font-styles seem to be ok.
rough support for text background in styles like `murphy` using predrawn
rectangles (svg has no text background attribute).
things to improve:
- svg width attribute (`<svg width=""`)
- linenumbers
- highlighting
- embedded font
- tabwidth option
- margins?
- better position/width calculation (rectangles not correctly drawn on
resize)
> added svg formatter

- lexers/README.md
Even though I made a couple of lexers by now, I still struggled the last time with generating the required test data. The reason why is that the lexer's README file uses a different operating system than I have.
So this pull request expands that file with information about Windows. I also added a bit more information to explain what's going on. This hopefully makes it easier for others to contribute to Chroma.
> Improve info on test regeneration

- formatters/html/html.go
- formatters/html/html_test.go
I'm working on cleaning up Hugo's highlighting code and use https://github.com/yuin/goldmark-highlighting. We have had some ugly replace logic to get the "correct" HTML wrappers. We tried to fix this with a "wrapper func" in goldmark-highlighting, but I totally forgot the `LineNumbersInTable` option I assume that `PreventSurroundingPre` was added to allow custom pre wrappers, but that is hard to do when the code lives inside a table.
This PR should solve Hugo's problem, and It's hopefully not too intrusive...
/cc @yuin
> Add WithPreWrapper option

- cmd/chroma/main.go
- cmd/chromad/main.go
- formatters/api.go
- formatters/html/html.go
- formatters/html/html_test.go
This allows the boolean options to be reconfigured, e.g:
```go
options := getOptions()
options = append(options, html.WithLineNumbers(true))
```
Fixes #301
> Add bool argument to WithClasses, WithLineNumbers etc.

- lexers/m/mlir.go
Ensure at least one character is matched else lexing ends up making no forward progress.
> Avoid empty matches in MLIR lexer

- formatters/html/html.go
This currently works only when `html.WithClasses(true)` is used.
The same colors as for the pre-highlighted lines are used.
Only the line number is highlighted, so difficult to notice, but
better than nothing.
> Highlight the line number targeted by the URL anchor

- formatters/html/html.go
- formatters/html/html_test.go
Hey! Thanks for chroma! I'm using it with Hugo.
This PR solves a small issue with the line numbering indentation. `baseLineNumber` is not considered in the calculation; thus, the result is not aligned in situations like the following:
After the fix, it works as expected:
Please, let me know if there is any aspect of the CL you'd like me to change or improve, and I'll be happy to do so.
P.S.: It still doesn't work for a negative `baseLineNumber`. I have the solution below – and more tests – but I'm not sure whether the added complexity is worth the rarest of usages. Please LMK what you think.
```diff
diff --git a/formatters/html/html.go b/formatters/html/html.go
index f0ef44a..5b2da5a 100644
--- a/formatters/html/html.go
+++ b/formatters/html/html.go
@@ -189,6 +189,9 @@ func (f *Formatter) …
```
> Consider baseLineNumber when calculating the column width

- lexer.go
- regexp.go
- regexp_test.go
ref #329
related https://github.com/gohugoio/hugo/issues/6596
I have been wondering if it is better to add this functionality to chroma in itself or chroma's client (such as Hugo) because it will be a breaking change somehow.
Walking around chroma's source code and playing with [your online demo](https://swapoff.org/chroma/playground/) (it always uses `\n` and works fine), I am inclined to implement this functionality on chroma rather than on its client because I assume that logics behind chroma expect `\n` as EOL .
So I added `EnsureLF` as `TokeniseOption` and the default values is true.
Any comments are welcome.
> Add new TokeniseOption EnsureLF

- lexers/internal/api.go
- lexers/lexers_test.go
The following benchmark test:
```go
func BenchmarkGet(b *testing.B) {
for i := 0; i < b.N; i++ {
lexers.Get("go")
}
}
```
Shows the following results
```
go test -bench BenchmarkGet -run BenchmarkGet -v
```
```
goos: darwin
goarch: amd64
pkg: github.com/alecthomas/chroma/lexers
BenchmarkGet
BenchmarkGet-4   	    9336	    128457 ns/op
PASS
ok  	github.com/alecthomas/chroma/lexers	1.491s
```
Which is not so fast for a function that simply returns a lexer for a language. The reason is that we always try to find a lexer by a filename: https://github.com/alecthomas/chroma/blob/master/lexers/internal/api.go#L54. It has been done due to https://github.com/alecthomas/chroma/issues/94.
@alecthomas what do you think about returning a lexer if we found one by a provided name and only if we didn't …
> Improve performance of lexers.Get function

- formatters/html/html.go
- formatters/html/html_test.go
The `--all-styles` option currently produces invalid css for the `Text` token, because it doesn't have an associated class name.
The invalid css is `/* Text */ .chroma . {  }` and can be reproduced by running `chroma --html-styles --html-all-styles`.
More discussion about this issue at https://github.com/gohugoio/hugo/issues/7207
> Fix invalid css when all styles is used

- lexers/b/bash.go
- lexers/testdata/bash.actual
- lexers/testdata/bash.expected
Fixes https://github.com/alecthomas/chroma/issues/318
| Before | After |
| -- | -- |
| <img width="174" alt="Screen Shot 2020-05-09 at 15 11 37" src="https://user-images.githubusercontent.com/329222/81474682-6d09b300-9207-11ea-9b00-656bf9a96f00.png"> | <img width="160" alt="Screen Shot 2020-05-09 at 15 11 15" src="https://user-images.githubusercontent.com/329222/81474687-6ed37680-9207-11ea-8fb2-74f5fa0a35ef.png"> |
> Bash: Parse single comment mark as comment

- lexers/t/toml.go
I added curly braces to the TOML lexer. This should fix the error formatting of inline tables.
https://github.com/toml-lang/toml#user-content-inline-table
I have no go experience and did not test the build, so please excuse if this brakes everything ;-)
> added curly braces to toml lexer

- .travis.yml
https://github.com/alecthomas/chroma/commit/2b9ea60d89edafe3fa89fd5443cb818f4b3be222 updated the version but removed the `v` prefix which I think is what makes the download fail.
> Fix golangci-lint download

- lexers/i/ini.go
`.editorconfig` files [are ini](https://editorconfig.org/#file-format-details). Also tested on the playground and looks well.
> Add .editorconfig to ini lexer

- lexers/g/go.go
- lexers/testdata/go.actual
- lexers/testdata/go.expected
To allow proper detection of single line comments when there is no \n
Fixes #380
> Use EnsureNL for go lexer

- lexers/b/bash.go
`*.env` files are often used to hold environment variables which are in the format of restricted `sh`- syntax.
I'm not sure if the `.env` entry is necessary or if it will be covered by `*.env`.
> add *.env to bash lexer

- README.md
- formatters/html/html.go
- formatters/html/html_test.go
Currently its already possible to make line lumbers linkeable. Getting
such a link however requires the end user to look at the pages source
and then to manually edit the URL, which is not a great UX.
This PR changes that to make the line numbers a link to themselves, so
clicking on them gives a link to that line that can then be passed
around, similiar to e.G. GitHub.
Thanks for this great project btw!
> Make linkeable lines a link to themselves

- README.md
- table.py
This PR update the `table.py` script allowing to write the content directly into `README.md` to avoid manual actions and maybe could be useful to automate the release steps.
The table of supported languages was update using the script.
I tried to keep the script as simple and flat as possible, using only Python 3.x built-in functions. I though about the idea to implemented with a `--write-in-place` option but I don't know if it worth it.
In any case, feel free to request any changes you think could be appropriate, provide any feedback, or even just drop this PR because I know that adding more code implies more maintenance. Thanks for your time!
> Update supported languages table

- lexers/c/css.go
Fix function that include parenthesis shows a wrong syntax error #436.
after this patch
> Fix CSS lexer

- lexers/h/hlb.go
- lexers/q/qml.go
This PR moves `hlb` and `qml` lexers to correct subfolders.
> Move lexers to correct folders

- lexers/circular/php.go
- lexers/g/go.go
- lexers/p/python.go
Most languages allow for underscore in number literals. Fix support for a few
languages. References:
- https://docs.python.org/reference/lexical_analysis.html#integer-literals
- https://golang.org/ref/spec#Integer_literals
- https://php.net/language.types.integer
> LiteralNumberHex: underscore support

- style.go
- style_test.go
For example, if `chroma` is invoked on the command line, `LineNumbers`, `LineHighlight` et al are ignored.
> fix: synthesisable entries are ignored when cloned

- lexers/circular/php.go
- lexers/circular/phtml.go
I had an issue with gitea where syntax highlighting of PHP code mixed with HTML was not working, in reviewing we identified that the tag changes were made and the PHTML lexer was created in order to allow syntax highlighting of PHP code without the starting tag in markdown snippets (https://github.com/alecthomas/chroma/issues/210). These changes, however, cause issues when the PHP lexer is identified to parse files with the extension of `.php`.
For an example, with the file name/mime matches being on the PHP lexer, if we were to identify this file with either the mime type or file name, the PHP lexer will be used and the file will be highlighted incorrectly.
https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentytwentyone/template-parts/content/content-page.php
I …
> File name matches and mime matches should be moved to phtml from php lexer

- lexers/r/raku.go
Reduces package init costs from:
```
init github.com/alecthomas/chroma/lexers/r @3.2 ms, 0.41 ms clock, 69640 bytes, 571 allocs
```
to:
```
init github.com/alecthomas/chroma/lexers/r @5.7 ms, 0.015 ms clock, 3328 bytes, 57 allocs
```
> Convert raku to lazy lexer

- lexer.go
In the current state, lexers that have names that begin with lower case characters are all sorted at the bottom.
For example, the end of the `chroma --list` cli command is this
```shell
YANG
aliases: yang
filenames: *.yang
mimetypes: application/yang
Zig
aliases: zig
filenames: *.zig
mimetypes: text/zig
cfstatement
aliases: cfs
markdown
aliases: md mkd
filenames: *.md *.mkd *.markdown
mimetypes: text/x-markdown
mcfunction
aliases: mcfunction
filenames: *.mcfunction
plaintext
aliases: text plain no-highlight
filenames: *.txt
mimetypes: text/plain
reStructuredText
aliases: rst rest restructuredtext
filenames: *.rst *.rest
mimetypes: text/x-rst text/prs.fallenstein.rst
react
aliases: jsx react
filenames: *.jsx *.react
mimetypes: text/jsx text/typescript-jsx
reg
aliases: registry
filenames: …
```
> sort lexers with lower case

- lexers/t/toml.go
The current TOML lexer doesn't consider `-` as valid part of a TOML key, but this is [legal per the v1.0.0 TOML spec](https://toml.io/en/v1.0.0#keys). In the wild, this is the style used in `pyproject.toml` files.  
This patch makes the lexer use the same character ranges as the ones specified by the spec.
> toml: allow `-` in keys

- lexers/internal/api.go
Perhaps not the cleanest way to do this, but conveys the idea and results in a small diff.
> lexers: match known backup filename suffixes

- lexers/README.md
- lexers/lexers_test.go
This PR makes it possible to have several test files for a same lexer, by placing them in a directory—named after the lexer—in `testdata/`.
The underlying reasons for this PR are:
* make it easier to create independent tests for a same lexer, and therefore improve the overall robustness;
* make debugging easier in case of test failure (since it becomes possible to write different tests that test different features);
* allow easy import of [existing Pygments tests](https://github.com/pygments/pygments/tree/2.9.0/tests/snippets) into Chroma.
> Allow several tests for a same lexer

- lexers/f/fortran_fixed.go
This PR ports the FortranFixedLexer from pygments using the bundled tools and some manual tweak. It works on ScaLapack code so I think it generally shall work. It addresses #492
> Add FortranFixedLexer

- lexers/h/http.go
- lexers/r/raku.go
- lexers/r/rst.go
- regexp.go
- types.go
Useful for accessing named capture groups and context set by
`mutators` and other fields and methods LexerState provides.
I don't know if you'll accept this pull request, or if I did it the right way, cause I
don't know enough Go. But you mentioned it [here](https://github.com/alecthomas/chroma/issues/306#issuecomment-559304648).
I tried to make an `Interface` without changing the current emitters and tried
different things, the only thing that worked was changing the type of `Rule`
to an `interface{}` and type assert it while emitting the rule. For example:
``` go
if se, ok := rule.Type.(StateEmitter); ok {
l.iteratorStack = append(l.iteratorStack, se.StateEmit(l))
} else if e, ok := rule.Type.(Emitter); ok {
l.iteratorStack = append(l.iteratorStack, e.Emit(l.Groups, l.Lexer))
} else { …
```
> Pass `*LexerState` as context to emitters

- lexers/r/raku.go
- regexp.go
When generating the regex to match a string that belongs to a word list, and when one word of that list is a prefix of another, the former must come after the latter in the regex. This is because the regex parser is lazy about alternatives within a group, and stops at the first match; while the expected behavior is obviously greedy.
For instance (with keywords that can be found in Python): ```Words(``, ``, `yield`, `yield from`)``` without sorting would generate `(yield|yield from)`, a regex equivalent to `(yield)` (since when the ` from` suffix is here, the parser would stop after having matched `yield`).
A simple solution to solve this is to sort all words by descending length, which is sufficient to guarantee the aforementioned constraint.
*Performance note: it would be possible to …
> Fix: sort words in descending order of length before regex generation

- README.md
- cmd/chroma/main.go
Makes use of chroma easier in/as less(1) preprocessors.
https://manpages.debian.org/less#INPUT_PREPROCESSOR
```shell
export LESSOPEN='| p() { chroma --fail "$1" || cat "$1"; }; p "%s"'
```
https://manpages.debian.org/lesspipe#USER_DEFINED_FILTERS
```shell
ln -s ~/go/bin/chroma ~/.lessfilter
```
> cmd: add optional silent fail mode on no specific lexer

- lexers/internal/api.go
The .in suffix is often assiociated with build system input/template
files, for example in autotools ones.
> feat(lexers): match filenames ignoring trailing .in

- regexp.go
To better match vanilla Go regexps and support some additional
constructs that might be present in Pygments rules.
https://github.com/dlclark/regexp2#re2-compatibility-mode
> feat(regexlexer): compile in RE2 compatibility mode

- regexp.go
It's useful for cases where there are capturing groups inside capturing groups and you only want the outer group and skip the inner groups.
> Allow skipping group's emitter, via passing nil as emitter

- regexp.go
- regexp_test.go
To be used like this:
```go
ByGroupNames(map[string]Emitter{
`key`: Keyword,
`operator`: Operator,
`value`: String
})
```
> Add ByGroupNames function, same as ByGroups but use named groups

- lexers/c/c.go
Copied the KeywordType rule from the c++ lexer (but removed wchar_t since it doesn't exist in c).
Unfortunately, I can't test it since I'm unfamiliar with go.
> Added uint8_t to c lexer.

- lexers/f/fish.go
- lexers/testdata/fish.actual
- lexers/testdata/fish.expected
Command line arguments containing dash/hyphen were incorrectly tokenised as command line options.
> fish: Fix incorrect tokenisation of command arguments containing dash

- README.md
Per: https://github.com/alecthomas/chroma/issues/528#issuecomment-866370115
> Use the release binaries. go get is not supported anymore.
> Remove `go get` for installation from README

- lexers/internal/api.go
https://manpages.debian.b/bullseye/ucf/ucf.1.en.html
> lexers: add Debian user configuration file backups to ignored suffixes

- lexers/j/json.go
JSON spec doesn't allow comments, but many implementations support them anyway. Having comments is very convenient, for example, when showing code in blog posts and articles.
> Support comments in JSON

- lexers/b/bashsession.go
- lexers/testdata/bashsession.actual
- lexers/testdata/bashsession.expected
A basic bash-session lexer, addressing #137.
The idea was to start simple (cover 80% of use cases) and evolve the lexer as needed -- I'd rather have this than no console lexer at all 😄.
/cc @nate-double-u
> BashSession lexer

- lexers/internal/api.go
This package appears to be old and unmaintained, and it gets pulled into the
go.sum of every single package importing Chroma. Also fnmatch doesnt seem to do
any error checking on the pattern, while the standard package does. Also, the
standard package path/filepath is already imported, so it appears not to cost
anything to change it.
> lexers/internal: remove danwakefield/fnmatch

- styles/witchhazel.go
https://witchhazel.thea.codes/
> Add WitchHazel by Thea Flowers

- formatters/html/html.go
- formatters/html/html_test.go
Apparently only "phrasing content" are permitted inside `pre` and `code`, and `div` is not one of them, so replaced it with `span`, `div` wasn't necessary anyway.
Also it makes sense to put code inside `code` tag(except for line numbers).
Removed `overflow:auto` and `width: auto` from `table` as they didn't seem to be necessary and actually prevented horizontal scroll bar to appear when content didn't fit in the viewport.
> [HTML formatter] Use `span` for `.line`, put code inside `<code>`

- lexers/s/scheme.go
Currently, some characters are not detected and some strings are detected as characters while they shouldn't. Example from the playground :
This PR fixes this. Example from running patched chroma binary in a terminal :
> Fixed scheme characters

- lexers/b/bicep.go
As discussed in the other PR #573, the MimeType for the Lexer Bicep has been removed.
> Removed mimetype for the Lexer bicep

- lexers/x/xml.go
Add support for highlighting MSBuild project files for C# (.csproj), F# (.fsproj), and C++ (.vcxproj), which are XML based.
Reference:
* https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=msvc-170
* https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#project-files
> Highlight MSBuild project files for C#, F#, and C++ as XML.

- _tools/pygments2chroma.py
Link to the breaking change: [L194](https://github.com/alecthomas/chroma/commit/59896e35\#diff-636cb338885284f1ed8524116f49b2bffcae81cfce89f55719019c993007d209R194)
I assume this is an accident that was overlooked for a few weeks.
> fix: revert line change from pygments converter 59896e35

- formatters/html/html.go
- formatters/html/html_test.go
Example:
``` go
WithCustomCSS(map[chroma.TokenType]string{chroma.Line: `display: inline;`})
```
Should fix the second issue of #617!
This with #618 should fix both issues of #617 unless I missed something.
> [html formatter] Add option to let users provide custom CSS styles

- lexers/embedded/kotlin.xml
This adds the [`value` keyword](https://kotlinlang.org/docs/inline-classes.html) for Kotlin.
> Add value keyword for Kotlin

- formatters/html/html.go
- formatters/html/html_test.go
- Add an `InlineCode` option for inline code blocks, which wraps the code in `code` tag and doesn't wrap the code by `Line` and `CodeLine`
- When `PreventSurroundingPre` option is enabled, do not wrap the code by `Line` and `CodeLine`
- Write and update related tests
- Fixes #617
Please test and review if this behavior is desired and correct.
Specially `PreventSurroundingPre`, is everyone OK with this behavior?
> Add `InlineCode` option for inline code blocks

- styles/github-dark.go
The PR updates a couple of styles and reformats the code to keep consistent with the Pygments version that just got merged — pygments/pygments#2192 — for easier maintenance.
> fix(styles/github-dark): update definitions, reformat

- lexers/embedded/javascript.xml
.cjs is used to indicate a CommonJS in Node.js and other tools
> Add cjs to Javascript lexer

- lexers/embedded/cfengine3.xml
This rule is problematic for 2 reasons:
* The regex is buggy, it doesn't work for more advanced cases
when there are other attributes before slist, or string, or
whatever the type is.
* In the context of CFEngine policy language, it's just a bit
confusing. Yes, they are variable names, but they are also
quoted strings, and what we call promisers. It looks better,
more consistent and less confusing if they are highlighted
in the same way as other strings and promisers.
**Before:**
**After:**
> cfengine3: Removed rule attempting to highlight variable names

- lexers/embedded/gas.xml
Support for the latest version of Pygments
> Update GAS lexer

- colour.go
- colour_test.go
- style.go
- style_test.go
These functions can make it easier to to update a style's
contrast when viewed against light and dark backgrounds.
See #353.
Also avoid a segfault when Get is called on a StyleBuilder
that was created using NewStyleBuilder (as opposed to
Style.Builder).
> Add Colour.ClampBrightness and StyleBuilder.Transform.

- cmd/chroma/main.go
Exposes HTML Linkable Lines option to the CLI
Addresses #678
> Add linkable line number option to CLI

- _tools/pygments2chroma_xml.py
This script automatically generates a lexer in xml format from Pygments.
Test Code:
```sh
python3 ./pygments2chroma_xml.py pygments.lexers.c_cpp.CppLexer > lexer.xml && xmllint --format -o cpp_lexer.xml lexer.xml
```
I tested the script on some languages e.g. gas, cpp, python, spl and it worked fine till generating xml files.
However, some grammar emits validation error at formatting phase.
The problem is `state redefinition` like this:
```xml
<push state="#pop" state="root"/>
```
Although the script is not perfect, it will make it easier to update the lexers.
> Add pygments2chroma_xml.py

- lexers/embedded/fsharp.xml
- lexers/testdata/fsharp/fsharp_open_static_class.actual
- lexers/testdata/fsharp/fsharp_open_static_class.expected
Hello,
*Disclaimer: I am new to Go, so I am unsure if what I did is all that is needed*
In F# it is now possible to open static class using `open type` syntax. 
[F# documentation](https://docs.microsoft.com/fr-fr/dotnet/fsharp/language-reference/import-declarations-the-open-keyword#open-type-declarations)
This PR tries to add support for this syntax.
In the test code, that I used I wanted to check that it the highlith worked for both top level instruction and instructions indented inside of a module.
> Add support for F# open static class

- styles/catppuccin.go
Resolves #684 
Implements the **mocha** variant of [catppuccin](https://github.com/catppuccin/catppuccin). Back when I made the original, mocha was the original and only palette, which is why it's the only one I've included in this PR.
Let me know if you'd like the other variants, or someone else can add them in a follow-up PR. I have all of them generated over at https://github.com/jolheiser/chroma-catppuccin 🙂 
I've made this theme `catppuccin` rather than `catppuccin-mocha` simply because it was the original variant, but let me know if you'd like to "fully qualify" it as `catppuccin-mocha` for future-proofing reasons.
> Add catppuccin mocha style

- styles/rose-pine-dawn.go
- styles/rose-pine-moon.go
- styles/rose-pine.go
> Feat: Add Rosé-Pine variants

- lexers/README.md
It's `go test ./lexers` and not `go tests ./lexers`
> Fix typo in README

- lexers/embedded/c.xml
Sorry, I was wrong on #701 This should fix the problem of not highlighting functions.
See the screenshot below:
> Fix a bug that ate functions on C lexer

- lexers/embedded/powershell.xml
- lexers/testdata/powershell.actual
- lexers/testdata/powershell.expected
Problem:
Variables inside doublequoted strings were not highlighted properly in PowerShell. The variables looked like they do when using singlequoted strings.
Solution:
Added rules and tests for variables inside doublequoted strings in PowerShell.
It took me a while to understand how the lexers work, but I think I have understood it properly. I could not find any contributing guidelines so I hope I have not broken any rules now :)
> Improved PowerShell lexer

- README.md
- lexers/make.go
For display purpose, it would be better if this lexer is just named "Makefile". Can we rename lexers without breaking integrations?
I think the name comes from `pygments.lexers.make.BaseMakefileLexer` which is in `pygments-lexers.txt`, but as there is no other Makefile lexer, I think the prefix could be dropped.
> Rename 'Base Makefile' lexer to 'Makefile'

- lexers/embedded/nim.xml
Fixes #725.
Without patch, incorrect highlighting:
With patch, correct highlighting:
> Add missing type suffixes for Nim

- lexers/embedded/php.xml
currently phtml takes priority over php, that's odd considering phtml is not very common anymore compared to php
Fixes #577
> increase php priority over phtml

- cmd/chroma/main.go
- lexers/embedded/holyc.xml
I've tried to add HolyC support by cross referencing GitHub's Linguist HolyC implementation against it's C implementation to see how the syntax is different. Then copied the C file on Chroma and applied those changes. This hopefully should work.
> Add HolyC support

- lexers/embedded/z80.xml
This handles most Z80 instructions and commonly-used assembler directives, but does not impose much structure beyond recognizing those items.
> Add Z80 assembly lexer

- styles/vulcan.xml
> styles/vulcan: Fix background color

- cmd/chromad/main.go
While testing on a VM, if the steps described in #757  also works on Windows, I found out, that the Playground is broken. The reason is, that it doesn't use the correct mime type for JavaScript for some reason. This fixes it.
> Fix Playground on Windows

- lexers/embedded/python.xml
- lexers/testdata/python/test_structural_pattern_matching.actual
- lexers/testdata/python/test_structural_pattern_matching.expected
> [Python]Add match and case to Keywords

- README.md
This will make it clearer where the tests are.
When I first contributed I didn't see past the "try it with chromad" instructions.
> Update the main README to point to the lexers/README

- styles/nord.xml
Right now there is no value for NameOther making .chroma .nx to be empty.
Because of that there are cases in which the color is wrongly used because it's not overwritten (for eg: when trying to use a light theme as the main one, and Nord under prefers-color-scheme: dark .
This MR sets the color to match the one from the theme preview.
Before:
After:
> FIX: update nord theme to have a base color for NameOther

- styles/nord.xml
Right now there is no value for NameProperty making .chroma .py to be empty.
Because of that there are cases in which the color is wrongly used because it's not overwritten (for eg: when trying to use a light theme as the main one, and Nord under prefers-color-scheme: dark .
This sets the color to match the one from the theme preview that is applied for the methods
Before:
After:
> FIX: update nord theme to have a base color for NameProperty

- lexers/embedded/psl.xml
- lexers/testdata/psl.actual
- lexers/testdata/psl.expected
Improved the highlighting for PSL (Profile Scripting Language). This improves highlighting for numbers, variable names (which can start with . or %), various types of function calls, and language-specific directives.
The language documentation is not available to the public, so it's not easy to verify by non-FIS customers, but much of the highlighting is inspired by the grammar from FIS' PSL VS Code extension:  [https://github.com/ing-bank/vscode-psl](https://github.com/ing-bank/vscode-psl).
> Improve PSL directive, function, and variable name highlighting

- lexers/haxe.go
Prevents `runtime error: slice bounds out of range` when list is empty.
> Prevent panic from hax lexer

- lexers/cpp.go
This PR adds CPP lexer as well its analyzer as implemented in Pygments.
https://github.com/pygments/pygments/blob/master/pygments/lexers/c_cpp.py#L407
> Add CPP lexer

- lexers/cpp_test.go
- lexers/testdata/cpp_include.cpp
- lexers/testdata/cpp_namespace.cpp
This PR adds missing C++ tests for new function `AnalyzeText` implemented on #813.
> Add missing C++ tests

- lexers/c.go
- lexers/c_test.go
- lexers/testdata/c_ifdef.c
- lexers/testdata/c_ifndef.c
- lexers/testdata/c_include.c
This PR adds C lexer as well its analyzer as implemented in Pygments.
https://github.com/pygments/pygments/blob/master/pygments/lexers/c_cpp.py#L313
> Add C lexer

- lexers/cpp.go
This PR adds missing `.tpp` file extension to C++ lexer.
> Add .tpp as a c++ lexer file extension

- lexers/embedded/elixir.xml
This PR adds missing `.eex` Elixir file extension.
> Add .eex as a Elixir lexer file extension

- lexers/embedded/toml.xml
This PR adds missing `Pipfile` and `poetry.lock` TOML file extension.
> Add Pipfile and poetry.lock as a TOML lexer file extension

- lexers/embedded/iscdhcpd.xml
This PR solves the conflict between ApacheConf lexer and ISCdhcpd lexer where ISCdhcpd uses `*.conf` as filename which overloads ApacheConf that defines only `apache.conf`. To be error prune and less noisy I changed to `dhcpd.conf` as per the [docs](https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhcpdconf) say.
> Fix ISCdhcpd filename

- lexer.go
- lexers/embedded/c++.xml
- lexers/embedded/c.xml
- regexp.go
- serialise.go
This PR improves the regexes analysers in XML by adding the `single` attribute and changing how regex nodes are implemented. Some analysers break in the first match where others sum all scores and return, the `single` attribute when true returns the score for the first match. The regex order matters.
```xml
<analyse single="true" >
<regex pattern="(?m)^\s*#include &lt;" score="0.1" />
<regex pattern="(?m)^\s*#ifn?def " score="0.1" />
</analyse>
```
Ref #828
> feat: improve regex analysers in XML

- serialise.go
Some lexers would return a value more thant 1.0 for analyzing score. This PR ensures it won't take over the maximum value for it.
> feat: ensure the analyse score is up to 1.0

- registry.go
This PR avoids duplicity at global lexers. Sometimes lexers could be registered by the client and to avoid any incosistence between the same one a function `add` was implemented.
> Avoid duplicate lexer if already registered

- lexers/embedded/twig.xml
This PR adds missing `*.twig` file extension to Twig lexer.
> Add missing *.twig file extension

- lexers/embedded/gas.xml
This PR sets priority for `GAS` lexer over `ca 65 assembler` and `ArmAsm`.
> Set priority for GAS lexer

- lexers/embedded/ini.xml
The file extension `.inf` is far more common as `INI` than `Inform 6` since both share the same file extension.
https://en.wikipedia.org/wiki/INF_file
https://www.ifwiki.org/Inform_6
> Set priority for INI lexer over Inform 6

- lexers/embedded/nasm.xml
This PR sets priority for `NASM` over `TASM` as implemented in [Pygments](https://github.com/pygments/pygments/blob/1a48184b8bf373c7037d5cc3a7f0eef51c093140/pygments/lexers/asm.py#L721). It also adds `*.nasm` as a file extension supported in this lexer.
> Set priority for NASM lexer

- lexers/embedded/clojure.xml
These changes allow EDN files, together with the commonly used `application/edn` MIME type, to be highlighted as Clojure syntax.
Fixes #824
> Update clojure.xml to target EDN

- lexers/embedded/gdscript.xml
- lexers/embedded/gdscript3.xml
2 weeks ago `GDScript` was renamed to `GDScript3` adding support for v4 and added analyse regexes but it's wrong according to [Pygments](https://github.com/pygments/pygments/blob/1a48184b8bf373c7037d5cc3a7f0eef51c093140/pygments/lexers/gdscript.py#L171).
> Fix GDScript3 analyse regexes

- lexers/embedded/makefile.xml
Fixes https://github.com/alecthomas/chroma/issues/847.
> add justfile filename to Makefile lexer

- lexers/embedded/r.xml
Keywords like `function`, `for`, `if`, and `return` followed by parentheses were recognized as `NameFunction`; others like `in` were recognized as normal `Name`. This PR moves the rule for keywords to the top.
The code tested with `go run .` in `cmd/chromad`:
```r
printeven = function(n) {
for (i in seq_len(n)) {
if (i %% 2 == 0) {
print(i)
}
}
return(invisible(n))
}
```
the original result:
```html
<pre class="chroma"><code><span class="line"><span class="cl"><span class="n">printeven</span> <span class="o">=</span> <span class="nf">function</span><span class="p">(</span><span class="n">n</span><span class="p">)</span> <span class="p">{</span>
</span></span><span class="line"><span class="cl"> <span class="nf">for </span><span class="p">(</span><span class="n">i</span> <span …
```
> lexers/r: Match keywords prior to functions

- lexers/embedded/docker.xml
Add another filename variant. Seen in the wild [here](https://github.com/goauthentik/authentik/blob/main/radius.Dockerfile).
> Add `*.Dockerfile` to docker lexer

- formatters/tty_indexed.go
- formatters/tty_indexed_test.go
Before this change, asking `tty_indexed.go` for the `None` type ("No highlighting") returned an empty string.
With this change in place, asking `tty_indexed.go` for the `None` type returns (the closest it can get to) the same colour as `tty_truecolor.go`.
Relates to https://github.com/walles/moar/issues/161#issuecomment-1758393935.
> Make `tty_indexed.go` respond to `None` like `tty_truecolour.go`

- lexers/embedded/go_template.xml
According to [this](https://stackoverflow.com/questions/22254013), these two are the most popular.
There is also `.gohtml` and `.go.html` but it would need [multi-language highlighting](https://github.com/alecthomas/chroma/issues/783). Also, `.tmpl` is common, but it's already in-use by the cheetah lexer unfortunately.
EOL change is in conformance to [editorconfig](https://github.com/alecthomas/chroma/blob/b127e3569cecb6023e71df532c6d9f371d945914/.editorconfig#L13).
> Add file extensions to go_template lexer

- lexers/embedded/ucode.xml
The [ucode](https://ucode.mein.io/) language is "a tiny general purpose scripting language featuring a syntax closely resembling ECMAScript". It was created for use in OpenWrt, the Linux distribution commonly used in routers and other embedded devices.
I used the JavaScript lexer as the starting point, and removed the keywords not used in ucode (and added one or two).
Questions:
- What is the difference between `Keyword` and `KeywordReserved`? The JavaScript lexer uses both, but I don't see the pattern.
- Should `KeywordNamespace` be used for `import`, `as`, `from`, and maybe `export`? The JavaScript lexer does not use it, but the Python one does.
> Create lexer for ucode

- lexers/embedded/dns.xml
This commit fixes #885.
Before this commit, only the first part (before the first dot) of a domain name was highlighted as NameClass``, which made the rest highlight in `err` (red). This commit makes domain names anywhere in the line highlight as NameClass, still allowing @ at the start of a line to be highlighted just as before.
> fix(dns): highlight domain names as NameClass

- lexers/embedded/ruby.xml
[Vagrantfile](https://developer.hashicorp.com/vagrant/docs/vagrantfile) is pure Ruby.
> Add Vagrantfile to Ruby lexer

- styles/catppuccin-frappe.xml
- styles/catppuccin-latte.xml
- styles/catppuccin-macchiato.xml
- styles/catppuccin-mocha.xml
- styles/github-dark.xml
should address #910.
let me know if any color definition seems odd.
PS: also updated the auto-gen template [here](https://github.com/icy-comet/catppuccin-chroma-theme)
> styles(catpuccin/gh-dark): LineHighlight grp

- lexers/embedded/promela.xml
Small revisions to the recently merged Promela language support (#906).
> Promela Lexer: fix file extension typo, remove redundent parens

- lexers/embedded/rego.xml
Adapted heavily from several of the lexers in this repo, and
https://github.com/tsandall/vim-rego/blob/b47bf95996b72d630464b44ca567f2945bd37ac9/syntax/rego.vim
> Add support for Rego syntax

- lexers/embedded/json.xml
`.avsc` files are pure JSON.
References:
- https://avro.apache.org/docs/1.11.1/getting-started-java/#defining-a-schema
- https://github.com/github-linguist/linguist/blob/559a6426942abcae16b6d6b328147476432bf6cb/lib/linguist/languages.yml#L3148
> Add .avsc to JSON lexer

- formatters/html/html.go
- formatters/html/html_test.go
```
🐚 ~/dev/chroma $ benchcmp before.txt after.txt
benchmark                    old ns/op     new ns/op     delta
BenchmarkHTMLFormatter-8     160560        77797         -51.55%
benchmark                    old allocs     new allocs     delta
BenchmarkHTMLFormatter-8     1267           459            -63.77%
benchmark                    old bytes     new bytes     delta
BenchmarkHTMLFormatter-8     52568         25067         -52.32%
```
> feat: introduce a LRU compiled style cache for the HTML formatter

- lexers/embedded/c#.xml
- lexers/testdata/csharp/csharp_comment_single.actual
- lexers/testdata/csharp/csharp_comment_single.expected
- lexers/testdata/csharp/csharp_comment_summary.actual
- lexers/testdata/csharp/csharp_comment_summary.expected
Adjust the lexer of C# to properly lex empty comments. Test cases were added.
> C#: Allow for empty comments

- lexers/embedded/python.xml
https://bazel.build/concepts/build-ref
"such a boundary marker file could be MODULE.bazel, REPO.bazel, or in legacy contexts, WORKSPACE or WORKSPACE.bazel."
> Add Bazel bzlmod support into Python lexer

- lexers/embedded/org_mode.xml
- lexers/testdata/org.actual
- lexers/testdata/org.expected
- Move the `*` operator to inside the capturing group so all characters that match `\s` is preserved and not just the first character.
- Add tests.
- Resolves https://github.com/alecthomas/chroma/issues/845
<details><summary>Input</summary>
```orgmode
Generic text.
/Italicized/
*strong*
=Heading=
~Codeblock~
+StrikeTrough+
_Underlined_
```
</details>
> Org: Keep all newlines

- styles/tokyonight-day.xml
- styles/tokyonight-moon.xml
- styles/tokyonight-night.xml
- styles/tokyonight-storm.xml
Add [`tokyonight`](https://github.com/folke/tokyonight.nvim) based styles.
`tokyonight-storm`
`tokyonight-day`
`tokyonight-moon`
`tokyonight-night`
> chore(styles): add tokyonight inspired styles

- styles/nordic.xml
I added the "Nordic" theme from [AlexvZyl's](https://github.com/AlexvZyl) project [nordic.nvim](https://github.com/AlexvZyl/nordic.nvim).
All colors are cross referenced from the nordic theme and matches 95% of syntax highlighting exactly.
Thanks!
> added the nordic theme via chroma/styles/nordic.xml

- lexers/embedded/hare.xml
Adds the `done` keyword described in [this blog post](https://harelang.org/blog/2024-04-01-introducing-for-each-loops-in-hare/) and introduced in [0.24.2-rc1](https://lists.sr.ht/~sircmpwn/hare-dev/%3CD2FVIMECX52X.2MYXMW7OG4UIK@cmpwn.com%3E).
> feat(lexers/hare): add done keyword

- _tools/pygments2chroma_xml.py
Discovered while building on top of https://github.com/alecthomas/chroma/issues/877#issuecomment-1858982870 (by @miliog)
The pygments "regex.words" should be escaped, since they may contain special regex chars (like `^` or `+`).
> pygments2chroma: escape regex.words

- lexers/go.go
- lexers/testdata/go.actual
- lexers/testdata/go.expected
This PR changes `CommentSingle` to not consume the newline at the end as a part of comment.
That solves the problems of single line comment being not parsed at the end of the line or at the end of the file. Which was reported earlier as the reason to not highlight single line comment properly.
Disabling `EnsureNL: true` does not add unnecessary newline element for `Text`, `CommentSymbol` symbols. Using chroma in console with syntax highlighting was unusable becasue of this, since typing e.g. `b := ` adds newline each time space is at the end when host app asks for highlighted text from `quick`.
Tokens behavior:
<table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td>
``` go
t.Run("Single space", func(t *testing.T) {
tokens, _ := chroma.Tokenise(Go, nil, " ")
expected := …
```
> Go lexer: single line comment without consuming endline, disable EnsureNL

- styles/github.xml
I noticed that the current syntax highlighting generator uses an older color palette that doesn’t reflect GitHub’s latest light theme, which now features lighter, pastel tones for improved readability and accessibility. I’ve updated the color scheme to match the newer colors.
I was wondering if it makes sense to adopt these changes or, if maintaining the current color scheme is essential, whether it would be better to publish this as a separate variant under a different name.
> Update GitHub light color palette

- formatters/tty_indexed.go
- formatters/tty_truecolour.go
Let's say a pager, like [moar](https://github.com/walles/moar) (uses Chroma for syntax highlighting) or `less`, shows a line in the middle of a file.
Unless that line starts with the correct formatting for the line, the pager would have to scan the whole file from the start to get the coloring of this single line right.
Before this PR, lines were not guaranteed to start with formatting, but could sometimes rely on formatting from the preceding lines.
With this change in place, lines can now stand by themselves, and paging will work better on Chroma's output.
Missing formatting at the start of the line would happen when a token had a linefeed in the middle.
> Pager friendly terminal formatting

- lexers/go.go
Thanks for this awesome go module.
I have noticed that the builtin `any` type in Go isn't highlighted, so i have added it in this PR. :)
> add any as a builtin type for go

- lexers/embedded/json.xml
JSONC is JSON with comments. The JSON lexer already supports comments.
> feat(JSON): support `.jsonc` extension

- lexers/embedded/nix.xml
The nix lexor was missing the '=' operator in the operators rule. This meant that in some cases (like the first '=' in a code block), it would return an err instead of the proper highlighting.
Before:
After:
> fix(nix): nix lexor missing '=' operator

- lexers/embedded/lua.xml
Treat `*.luau` the same as `*.lua`. Same as Linguist does:
https://github.com/github-linguist/linguist/blob/c959cb53f48552db0e42cded66f3e5a64749b9ec/lib/linguist/languages.yml#L4109-L4120
> Add luau file extension and alias to lua lexer

- lexers/lexers.go
- lexers/lexers_test.go
- registry.go
`lexers.Aliases()` method shows all the aliases for all the available lexers, or their name if none are found. Using a flag, lexers without aliases can be skipped entirely.
This request addresses https://github.com/alecthomas/chroma/issues/1048.
> Add lexers.Aliases() method to display only lexers' aliases

- README.md
Since [moar](https://github.com/walles/moar?tab=readme-ov-file) is a useful command line app that showcases Chroma's highlighting capabilities, it makes sense to mention moar in the Command-line interface section of the README.
> Link to Chroma-using pager in README.md

- styles/rrt.xml
This will **at the very least** enable proper styling of `diff` files:
Before:
After:
Also added GenericStrong and GenericEmph tokens since they seem to be universal (but were missing).
The styling has been kept true to the rrt theme.
Fixes #603
> styles: add proper diff styling to rrt (fix #603)

- formatters/html/html.go
Currently when writing the css file comments before each class is present.
```css
/* Background */ .bg { color: #cdd6f4; background-color: #1e1e2e;-moz-tab-size: 2; -o-tab-size: 2; tab-size: 2; }
/* PreWrapper */ .chroma { color: #cdd6f4; background-color: #1e1e2e;-moz-tab-size: 2; -o-tab-size: 2; tab-size: 2; }
/* Error */ .chroma .err { color: #f38ba8 }
/* LineLink */ .chroma .lnlinks { outline: none; text-decoration: none; color: inherit }
/* LineTableTD */ .chroma .lntd { vertical-align: top; padding: 0; margin: 0; border: 0; }
/* LineTable */ .chroma .lntable { border-spacing: 0; padding: 0; margin: 0; border: 0; }
/* LineHighlight */ .chroma .hl { background-color: #45475a }
...
```
(Also why is there a .bg class, feels like that could collide)
This is probably a micro-optimization …
> feat(formatter): add writeCSSComments option

- lexers/embedded/docker.xml
btw. tinygo can be replace with just go
```Makefile
cmd/chromad/static/wasm_exec.js: $(shell go env GOROOT)/lib/wasm/wasm_exec.js
install -m644 $< $@
cmd/chromad/static/chroma.wasm: cmd/libchromawasm/main.go
GOOS=js GOARCH=wasm go build -o $@ $<
```
> correct lexing AS keyword for docker

- README.md
Ref: https://github.com/walles/moor/pull/305
The old GitHub project was renamed, and now redirects to the new one, so if you want to verify this is the same project, go to the old project and you will be redirected:
```https://github.com/walles/moar/pull/305```
> `moar` has been renamed to `moor`

- formatters/html/html_test.go
- iterator.go
When tokens are split into lines, tokens that end with a newline are emitted again as an empty token, which is confusing and doesn't have any benefit. This conversion shouldn't emit a empty tail token.
Adds a test.
I noticed this issue by a CI failure for the output of a Go program that was changed because of
d0ad67944442bcb84ff4710fe8dfa8f76ecedc01 and the new output contained a empty whitespace token at the beginning of most lines.
> fix: don't emit empty tail tokens

- styles/tango.xml
This makes Chroma's tango whitespaces match the original:
https://github.com/pygments/pygments/blob/0328cfaf1d953b3a0c7eb0ec0efd363deb2f9d51/pygments/styles/tango.py#L60
The underline looks like a rendering bug when marking text.
> tango: Don't underline whitespace

- lexers/embedded/ini.xml
Added the following file extensions to the `ini` lexer:
- .container
- .network
- .build
- .pod
- .kube
- .volume
- .image
see https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html
This is my first pull request :)
> Add file extensions for systemd units using Podman Quadlet
